name: MSVC build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.3

    - name: Build x86
      run: |
        mkdir x86 && cd x86
        cmake -G "Visual Studio 17 2022" -A Win32 .. -DBUILD_GMOCK=0
        msbuild GameCheats.sln /p:Platform=Win32 /p:Configuration=Release /m

    - name: Build x64
      run: |
        mkdir x64 && cd x64
        cmake -G "Visual Studio 17 2022" -A x64 .. -DBUILD_GMOCK=0
        msbuild GameCheats.sln /p:Platform=x64 /p:Configuration=Release /m

    - name: Test x86
      run: x86/Release/HackLibTests.exe

    - name: Test 64
      run: x64/Release/HackLibTests.exe

    - uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: |
           x86/Release/*.exe
           x64/Release/*.exe
        if-no-files-found: error
