name: MSVC build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2

    - name: Build x86
      run: |
        mkdir x86 && cd x86
        cmake -G "Visual Studio 17 2022" -A Win32 .. -DBUILD_GMOCK=0
        msbuild GameCheats.sln /p:Platform=Win32 /p:Configuration=Release /m

    - name: Build x64
      run: |
        mkdir x64 && cd x64
        cmake -G "Visual Studio 17 2022" -A x64 .. -DBUILD_GMOCK=0
        msbuild GameCheats.sln /p:Platform=x64 /p:Configuration=Release /m

    - name: Test x86
      run: x86/Release/HackLibTests.exe

    - name: Test x64
      run: x64/Release/HackLibTests.exe

    - name: Print Hashes
      shell: pwsh
      run: |
        Get-ChildItem "x??/Release/*.exe" | Get-FileHash -Algorithm SHA256 | Format-List | Tee-Object Hashes.txt

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automated release (latest commit)"
          files: |
            Hashes.txt
            x64/Release/*.exe
            x86/Release/*.exe